USE CAVH3

SELECT * FROM SEGURO

SELECT* FROM INSCRIPCION

SELECT * 
FROM ALUMNO
WHERE AP_PATERNO='QUISPE' AND AP_MATERNO='OCANA' AND NOMBRE='RAFAEL'

SELECT CUPO_MAX-CUPOS_LLENOS AS CUPOS_DISPONIBLES
FROM PARALELO
WHERE ID_PARALELO='' AND GESTION=''

SELECT * FROM PARALELO

/****   procedimiento almacenado que aumenta el cupo de inscritos, cuando se realiza una inscripcion    ****/
SELECT * FROM PARALELO

DROP TRIGGER DISMINUIR_CUPOS
____________________________________________
CREATE TRIGGER DISMINUIR_CUPOS
	ON INSCRIPCION
	FOR INSERT
	AS
		DECLARE @PARALELO VARCHAR,
			 @GESTION VARCHAR,
			 @cupo_disp INT
		
		SELECT @PARALELO= ID_PARALELO , @GESTION= ID_GESTION
		FROM INSERTED
		
		SELECT @cupo_disp=CUPO_MAX-CUPOS_LLENOS
		FROM PARALELO,INSCRIPCION
		WHERE @PARALELO= PARALELO.ID_PARALELO AND @GESTION= INSCRIPCION.ID_GESTION
		
		IF @cupo_disp<=0 
			BEGIN
				RAISERROR('No existe cupo disponible ...', 16, 1)
				ROLLBACK
				RETURN
			END
		UPDATE PARALELO SET CUPOS_LLENOS= CUPOS_LLENOS+1
		WHERE @PARALELO= ID_PARALELO AND @GESTION=GESTION
		
	----------------------------------------------------
	-----------------------------------------------------	
		SELECT CUPO_MAX-CUPOS_LLENOS AS CUPOS_DISPONIBLES
		FROM PARALELO
		WHERE ID_PARALELO='1PRIM-A' AND GESTION='GES2012'
		
		
		UPDATE PARALELO SET CUPOS_LLENOS=CUPOS_LLENOS+1
		WHERE ID_PARALELO='1PRIM-A' AND GESTION='GES2013'
		
		DELETE INSCRIPCION
		
		SELECT * FROM INSCRIPCION
		SELECT * FROM PARALELO
INSERT INTO INSCRIPCION VALUES('INS0001','20/01/2013','GES2013','CESPEDES QUISPE RITA','AL001','1PRIM-A','EM002');
INSERT INTO INSCRIPCION VALUES('INS0002','20/01/2012','GES2013','CESPEDES QUISPE RITA','AL002','1PRIM-A','EM002');
INSERT INTO INSCRIPCION VALUES('INS0003','20/01/2012','GES2012','AL003','1PRIM-A','EM002');
INSERT INTO INSCRIPCION VALUES('INS0004','20/01/2012','GES2012','AL004','1PRIM-A','EM002');
INSERT INTO INSCRIPCION VALUES('INS0005','20/01/2012','GES2012','AL005','1PRIM-A','EM002');
